### PR TITLE
Add User to Group, done right!

### PR DESCRIPTION
**Pull request by TurnrDev**
I did #12 and #15 right! About to add another commit to add docs. One second :+1:

### CODE REVIEW

**Comment by namaggarwal** [comment]
This looks great to me. I will run some tests and merge this later. I will also make a release end of the month. Feel free to add more APIs before that.

**Comment by TurnrDev** [comment]
Brilliant! Thank you! Just so I know what environments I should be testing in, what versions of Python are you officially supporting?

**Comment by namaggarwal** [comment]
Hey, I want to support python 2.7+ and 3.5+

**Comment by namaggarwal** [comment]
Hey @JayTurnr 

Can you please add the new API in Readme.md in this PR.

Naman

**Comment by TurnrDev** [comment]
Will do!

**Comment by namaggarwal** [comment]
Closing as I am taking this in the new version of the API

**Pull request closed without merging**
