### PR TITLE
Add support for updateExpense and undeleteExpense.

### PR DESCRIPTION
**Pull request by jelmer**
This adds basic but tested support for updateExpense and undeleteExpense methods.

### CODE REVIEW

**Comment by technillogue** [comment]
@namaggarwal should I resolve conflicts on this?

**Comment by namaggarwal** [comment]
@technillogue You probably would need to rewrite this, Please feel free to go ahead and implement

**Comment by aayaffe** [comment]
What is preventing the merging of this pull request?

**Comment by CloCkWeRX** [comment]
> What is preventing the merging of this pull request?

* Conflicts
* Testing?

**Comment by jelmer** [comment]
I'm not planning on working on this further, but it'd be great to see somebody pick it up.

**Pull request closed without merging**
